### ISSUE TITLE
Define module abilities

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/Shifting-Reality-VR#5]
- 12 needed (6 human, 6 super human)

**Comment by gavinjalberghini** [comment]
1 - Linear motion
2 - Rotation
3 - Head bobbing
4 - Jumping
5 - Running
6 - Climbing
7 - Flying (Rocket Hands)
8 - Frictionless 
9 - Impulse
10 - Magnetic?
11 - Item creation? Terrain modifying?
12 - Destroy game objects

**Comment by gavinjalberghini** [comment]
1 - Linear motion: On trackpad touch. Left controller. Strafe forward, backward, left, and right at walking speed.

2 - Rotation: On trackpad touch. Right controller. Snap rotation. Left and right.

3 - Head bobbing: Implemented on top of linear motion as a new script. Same controller and controls. Head bobs while moving.

4 - Jumping: On forward trackpad click. Right controller. Jump.

5 - Running: On forward trackpad click. Left controller. Increase movement speed.

6 - Climbing: On trigger press collision with climbable object. Lock hand in position. Unlock player from gravity. Inverse hand movement drives body movement. On release of trigger gravity resumes.

7 - Flying: On grip click. Right controller. Generate motion from active hand based on orientation.

8 - Frictionless: Passive. Turn off kinetic

9 - Impulse: On grip click. Left controller. Generate explosive motion based on controller position relative to body position. 

10 - Magnetic: Passive. Magnetic game objects move towards player.

(NOTE: Most of the controller bindings are occupied at this point. I will need to look into a way to dynamically change them. Until that happens I am only going to stick with the first 10 modules.)

**Comment by gavinjalberghini** [comment]
Still Needed:

Magnetic
Grabbing
Head Bobbing

**Comment by dellangeloj** [comment]
Updated (?):

Human: 
Linear Motion
Jumping
Grabbing
Head Bobbing

Superhuman:
Zero Gravity
Magnetic
Impulse
Flying

**Comment by dellangeloj** [comment]
Let me know what is right and wrong

**Comment by gavinjalberghini** [comment]
Those are correct 👍

**Comment by dellangeloj** [comment]
Updated 2:

Linear Motion
Jumping
Shooting

Zero Gravity
Magnetic
Impulse
Flying

**Comment by gavinjalberghini** [comment]
Decided to not use magnetic. Otherwise the remaining abilities have been finalized.
